version: '3.8'

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dede
      MONGO_INITDB_ROOT_PASSWORD: dede
      MONGO_INITDB_DATABASE: admin
    volumes: #short syntax
      - "./data-mongo1:/data/db" 
  
  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dede
      MONGO_INITDB_ROOT_PASSWORD: dede
      MONGO_INITDB_DATABASE: admin
    volumes: #long syntax
      - type: bind
        source: "./data-mongo2"
        target: "/data/db"
        read_only: false