version: '3.8'

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dede
      MONGO_INITDB_ROOT_PASSWORD: dede
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example

  mongodb-express-example:
    image: mongo-express:latest
    container_name: mongodb-express-example
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dede
      ME_CONFIG_MONGODB_ADMINPASSWORD: dede
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    networks:
      - network_example
    depends_on: #agar dijalankan service mongodb-example terlebih dahulu
      - mongodb-example


networks:
  network_example:
    name: network_example
    driver: bridge